# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.iu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerMain(object):
    def setupUi(self, registerMain):
        registerMain.setObjectName("registerMain")
        registerMain.setEnabled(True)
        registerMain.resize(432, 740)
        registerMain.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"}\n"
"\n"
"QWidget{\n"
"background-image: url(:/images/images/background.jpg);\n"
"}\n"
"\n"
"QFrame#contenedor{\n"
"background:#060921;\n"
"border-radius: 15px\n"
"}\n"
"\n"
"QToolButton{\n"
"background:#27587B;\n"
"border-radius: 15px\n"
"}\n"
"\n"
"QLabel#registro{\n"
"color: white;\n"
"font-size: 24px;\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"font-weight: bold;\n"
"color: white;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"border-bottom: 1px solid white;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"background:#27587B;\n"
"color: white;\n"
"border-radius: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#0E5386;\n"
"color: white;\n"
"border-radius: 15px;\n"
"font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(registerMain)
        self.centralwidget.setObjectName("centralwidget")
        self.contenedor = QtWidgets.QFrame(self.centralwidget)
        self.contenedor.setGeometry(QtCore.QRect(10, 10, 411, 721))
        self.contenedor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenedor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenedor.setObjectName("contenedor")
        self.icon = QtWidgets.QToolButton(self.contenedor)
        self.icon.setGeometry(QtCore.QRect(180, 40, 51, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon)
        self.icon.setIconSize(QtCore.QSize(30, 30))
        self.icon.setObjectName("icon")
        self.registro = QtWidgets.QLabel(self.contenedor)
        self.registro.setEnabled(True)
        self.registro.setGeometry(QtCore.QRect(60, 140, 131, 41))
        self.registro.setObjectName("registro")
        self.label = QtWidgets.QLabel(self.contenedor)
        self.label.setGeometry(QtCore.QRect(60, 190, 61, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.contenedor)
        self.lineEdit.setGeometry(QtCore.QRect(60, 220, 291, 20))
        self.lineEdit.setMaxLength(16)
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.contenedor)
        self.label_4.setGeometry(QtCore.QRect(60, 270, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.contenedor)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 300, 291, 20))
        self.lineEdit_4.setMaxLength(16)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.contenedor)
        self.label_5.setGeometry(QtCore.QRect(60, 360, 41, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.contenedor)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 390, 291, 20))
        self.lineEdit_5.setMaxLength(25)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.contenedor)
        self.label_6.setGeometry(QtCore.QRect(60, 440, 71, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.contenedor)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 470, 291, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(12)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.contenedor)
        self.pushButton.setGeometry(QtCore.QRect(54, 550, 291, 31))
        self.pushButton.setObjectName("pushButton")
        registerMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(registerMain)
        QtCore.QMetaObject.connectSlotsByName(registerMain)

    def retranslateUi(self, registerMain):
        _translate = QtCore.QCoreApplication.translate
        registerMain.setWindowTitle(_translate("registerMain", "Register"))
        self.icon.setText(_translate("registerMain", "..."))
        self.registro.setText(_translate("registerMain", "REGISTRO"))
        self.label.setText(_translate("registerMain", "Nombre/s"))
        self.lineEdit.setPlaceholderText(_translate("registerMain", "Nombre/s"))
        self.label_4.setText(_translate("registerMain", "Apellidos"))
        self.lineEdit_4.setPlaceholderText(_translate("registerMain", "Apellidos"))
        self.label_5.setText(_translate("registerMain", "Email"))
        self.lineEdit_5.setPlaceholderText(_translate("registerMain", "example@mail.com"))
        self.label_6.setText(_translate("registerMain", "Contraseña"))
        self.lineEdit_6.setPlaceholderText(_translate("registerMain", "************"))
        self.pushButton.setText(_translate("registerMain", "CREAR CUENTA"))
        
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerMain = QtWidgets.QMainWindow()
    ui = Ui_registerMain()
    ui.setupUi(registerMain)
    registerMain.show()
    sys.exit(app.exec_())
